services:
  db:
    image: mysql:latest
    container_name: ualaBackend_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
      - ${MYSQL_INITDB_SQL_FILE}:/docker-entrypoint-initdb.d/db.sql
    networks:
      - ualabackend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ualaBackend_app
    ports:
      - "9090:9090"  
    depends_on:
      - db
    networks:
      - ualabackend

networks:
  ualabackend:

volumes:
  database_mysql:
